import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static javax.swing.JOptionPane.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Enriquee
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Conexion con = new Conexion();
    Connection cn = con.Conexionn();
    public Principal() {
        initComponents();
        pnlInfBasica.setVisible(false);
        pnlMasInf.setVisible(false);
        if(("Buscar").equals(txtBuscar.getText())) lblBorrar.setVisible(false);
    }
 /*   public void mostrartabla(){
         DefaultTableModel tabla = new DefaultTableModel();
         tabla.addColumn("id");
         tabla.addColumn("nombre");
         tabla.addColumn("apellido");
         tabla.addColumn("edad");
         tabla.addColumn("correo");
         tblDatos.setModel(tabla);
         String sql ="SELECT * FROM usuario";
         String datos[]=new String[5];
         Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                tabla.addRow(datos);
            }
            tblDatos.setModel(tabla);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     } */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlLateral = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        lblBuscador = new javax.swing.JLabel();
        sptLinea1 = new javax.swing.JSeparator();
        lblBorrar = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlInfBasica = new javax.swing.JPanel();
        lblEdad = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMasInf = new javax.swing.JLabel();
        lblInfBasica = new javax.swing.JLabel();
        sptLinea = new javax.swing.JSeparator();
        sptLinea2 = new javax.swing.JSeparator();
        pnlMasInf = new javax.swing.JPanel();
        lblEdad1 = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblDomicilio1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblDomicilio2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox6 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 105, 247));
        setForeground(java.awt.Color.red);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 142, 198));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLateral.setBackground(new java.awt.Color(0, 100, 171));
        pnlLateral.setMaximumSize(new java.awt.Dimension(230, 590));
        pnlLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlLateralMouseDragged(evt);
            }
        });
        pnlLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLateralMousePressed(evt);
            }
        });
        pnlLateral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnlLateralKeyPressed(evt);
            }
        });
        pnlLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(0, 100, 171));
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setText("Buscar");
        txtBuscar.setBorder(null);
        txtBuscar.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        pnlLateral.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, 30));

        lblBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/search.png"))); // NOI18N
        lblBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscadorMouseClicked(evt);
            }
        });
        pnlLateral.add(lblBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 27));
        pnlLateral.add(sptLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 30));

        lblBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/borrar.png"))); // NOI18N
        lblBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBorrarMouseClicked(evt);
            }
        });
        pnlLateral.add(lblBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 30, 30));

        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flecha-simple-apuntando-a-la-izquirda.png"))); // NOI18N
        pnlLateral.add(lblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Volver");
        pnlLateral.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(pnlLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 590));

        pnlContenido.setBackground(new java.awt.Color(0, 104, 191));
        pnlContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlContenidoMousePressed(evt);
            }
        });
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cancel.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        pnlContenido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 30, 30));

        pnlInfBasica.setBackground(new java.awt.Color(0, 104, 191));
        pnlInfBasica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(204, 204, 204));
        lblEdad.setText("Edad");
        pnlInfBasica.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        lblApellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(204, 204, 204));
        lblApellido.setText("Apellido");
        pnlInfBasica.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        lblDomicilio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDomicilio.setForeground(new java.awt.Color(204, 204, 204));
        lblDomicilio.setText("Domicilio");
        pnlInfBasica.add(lblDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Domicilio");
        pnlInfBasica.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nombre...");
        pnlInfBasica.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Edad...");
        pnlInfBasica.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Apelido...");
        pnlInfBasica.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblNombre1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre1.setText("Nombre");
        pnlInfBasica.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        pnlContenido.add(pnlInfBasica, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 230, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/avatar.png"))); // NOI18N
        pnlContenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 150));

        lblMasInf.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblMasInf.setForeground(new java.awt.Color(204, 204, 204));
        lblMasInf.setText("Mas Inf.");
        lblMasInf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMasInfMouseClicked(evt);
            }
        });
        pnlContenido.add(lblMasInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, 20));

        lblInfBasica.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblInfBasica.setForeground(new java.awt.Color(204, 204, 204));
        lblInfBasica.setText("Basica");
        lblInfBasica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfBasicaMouseClicked(evt);
            }
        });
        pnlContenido.add(lblInfBasica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 20));
        pnlContenido.add(sptLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 80, 30));
        pnlContenido.add(sptLinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 80, 30));

        pnlMasInf.setBackground(new java.awt.Color(0, 104, 191));
        pnlMasInf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdad1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblEdad1.setForeground(new java.awt.Color(204, 204, 204));
        lblEdad1.setText("Correo");
        pnlMasInf.add(lblEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        lblApellido1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblApellido1.setForeground(new java.awt.Color(204, 204, 204));
        lblApellido1.setText("Enfermedades");
        pnlMasInf.add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 20));

        lblDomicilio1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDomicilio1.setForeground(new java.awt.Color(204, 204, 204));
        lblDomicilio1.setText("Historial");
        pnlMasInf.add(lblDomicilio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Historial...");
        pnlMasInf.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Telefono...");
        pnlMasInf.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Correo..");
        pnlMasInf.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblNombre2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre2.setText("Telefono");
        pnlMasInf.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        lblDomicilio2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDomicilio2.setForeground(new java.awt.Color(204, 204, 204));
        lblDomicilio2.setText("Estado de salud");
        pnlMasInf.add(lblDomicilio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Estado de salud...");
        pnlMasInf.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(0, 104, 191));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Anorexia ");
        jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/comprobado.png"))); // NOI18N
        pnlMasInf.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(0, 104, 191));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Diabetes");
        jCheckBox2.setIconTextGap(2);
        jCheckBox2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/comprobado.png"))); // NOI18N
        pnlMasInf.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(0, 104, 191));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Aterosclerosis");
        jCheckBox3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/comprobado.png"))); // NOI18N
        pnlMasInf.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(0, 104, 191));
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Celiaquía");
        jCheckBox4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/comprobado.png"))); // NOI18N
        pnlMasInf.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(0, 104, 191));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Hipertensión ");
        jCheckBox5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/comprobado.png"))); // NOI18N
        pnlMasInf.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, 20));

        jRadioButton1.setBackground(new java.awt.Color(0, 104, 191));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Tipo 1");
        jRadioButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/boton-encendido-de-radio.png"))); // NOI18N
        pnlMasInf.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(0, 104, 191));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Tipo 2");
        jRadioButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/boton-encendido-de-radio.png"))); // NOI18N
        pnlMasInf.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jCheckBox6.setBackground(new java.awt.Color(0, 104, 191));
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Bulimia");
        jCheckBox6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/comprobado.png"))); // NOI18N
        pnlMasInf.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        pnlContenido.add(pnlMasInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 670, 330));

        jPanel1.add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     int xx,xy;
    private void pnlLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLateralMousePressed
       
       xx=evt.getX();
       xy=evt.getY();
    }//GEN-LAST:event_pnlLateralMousePressed

    private void pnlContenidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlContenidoMousePressed

    }//GEN-LAST:event_pnlContenidoMousePressed

    private void pnlLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLateralMouseDragged
      int x=evt.getXOnScreen();
      int y=evt.getYOnScreen();
      this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_pnlLateralMouseDragged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void pnlLateralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlLateralKeyPressed
       setOpacity((float)0.8);
    }//GEN-LAST:event_pnlLateralKeyPressed

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
      if(("Buscar").equals(txtBuscar.getText()));
            txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
       if(("").equals(txtBuscar.getText()));
            txtBuscar.setText("Buscar");
    }//GEN-LAST:event_txtBuscarFocusLost

    private void lblBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscadorMouseClicked
       pnlInfBasica.setVisible(true);
       pnlMasInf.setVisible(false);
       lblBorrar.setVisible(true);
    }//GEN-LAST:event_lblBuscadorMouseClicked

    private void lblInfBasicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfBasicaMouseClicked
        while(txtBuscar.getText().equals("Buscar") || txtBuscar.getText().equals("")){
        if(txtBuscar.getText().equals("Buscar") || txtBuscar.getText().equals(""))showMessageDialog(this,"Ingrese un nombre");
        }
        pnlMasInf.setVisible(false);
        pnlInfBasica.setVisible(true);
    }//GEN-LAST:event_lblInfBasicaMouseClicked

    private void lblMasInfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMasInfMouseClicked
        do{
        pnlMasInf.setVisible(true);
        pnlInfBasica.setVisible(false);
        if(txtBuscar.getText().equals("Buscar") || txtBuscar.getText().equals(""))showMessageDialog(this,"Ingrese un nombre");
        }while(txtBuscar.getText().equals("Buscar") || txtBuscar.getText().equals(""));
    }//GEN-LAST:event_lblMasInfMouseClicked

    private void lblBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBorrarMouseClicked
        txtBuscar.setText("");
        pnlInfBasica.setVisible(false);
        pnlMasInf.setVisible(false);
    }//GEN-LAST:event_lblBorrarMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        pnlMasInf.setVisible(false);
        pnlInfBasica.setVisible(true);
        lblBorrar.setVisible(true);
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblBuscador;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblDomicilio1;
    private javax.swing.JLabel lblDomicilio2;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdad1;
    private javax.swing.JLabel lblInfBasica;
    private javax.swing.JLabel lblMasInf;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlInfBasica;
    private javax.swing.JPanel pnlLateral;
    private javax.swing.JPanel pnlMasInf;
    private javax.swing.JSeparator sptLinea;
    private javax.swing.JSeparator sptLinea1;
    private javax.swing.JSeparator sptLinea2;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
